image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - style

pylint:
  stage: style
  before_script:
    - pip install -r requirements.txt
  script:
  - find . -iname "*.py" | xargs pylint 
  only:
    - master
    - develop
